-- CXCAT-3355 is orign jira ticket

CREATE OR REPLACE VIEW CX_ANALYTICS_DEV.JEREMIAH_DEV_EXPLORATORY.CXCAT_712_CASE_DETAILS_RAW AS
SELECT
    -- 1. All Case Details
    C.*,
    
    -- 2. Context from the Error Event
    E.TIMESTAMP_UTC_DAY AS ORIGINATING_EVENT_DATE,
    E.ACTIVITY_NAME AS ORIGINATING_ERROR,
    E.UNHEALTHY_HOUSEHOLD_ID_COUNT,
    
    -- Keeping the ID visible to confirm it's fixed
    CAST(E.SONOS_ID AS NUMBER(38,0)) AS CLEAN_SONOS_ID

FROM 
    DATA_WAREHOUSE.WAREHOUSE_CUSTOMER.VIZ_OWNER_CSX_CONTACT_CASES_VOC C
INNER JOIN 
    PRODUCT_OWNER.RELIABILITY.HHH_DAILY_BY_ACTIVITY_NAME_SONOS_ID_AND_UNHEALTHY_ERRORS E
    ON CAST(E.SONOS_ID AS NUMBER(38,0)) = TRY_CAST(C.SONOS_ID AS NUMBER(38,0)) 
    AND C.CASE_CREATED_DATE_PT >= TO_DATE(E.TIMESTAMP_UTC_DAY)
    AND C.CASE_CREATED_DATE_PT <= DATEADD(day, 7, TO_DATE(E.TIMESTAMP_UTC_DAY))

WHERE 
    E.UNHEALTHY_HOUSEHOLD_ID_COUNT >= 1
    -- EXCLUSION LOGIC ADDED HERE:
    AND CAST(E.SONOS_ID AS NUMBER(38,0)) > 0  -- Removes 0 and negative values
    AND TRY_CAST(C.SONOS_ID AS NUMBER(38,0)) > 0; -- Ensures the Case side is also valid
